# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['server_installer.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Bundle entire project directories and files
        # These will be available in sys._MEIPASS when the executable runs
        ('../backend', 'backend/'),
        ('../frontend', 'frontend/'),
        ('../.gitignore', '.gitignore'),
        ('../create_service.ps1', 'create_service.ps1'),
        ('../database_schema.md', 'database_schema.md'),
        ('../DEPLOYMENT_QUICK_REFERENCE.md', 'DEPLOYMENT_QUICK_REFERENCE.md'),
        ('../DEPLOYMENT.md', 'DEPLOYMENT.md'),
        ('../docker-compose.yml', 'docker-compose.yml'),
        ('../multi_unit_simulation.py', 'multi_unit_simulation.py'),
        ('../QUICK_START.md', 'QUICK_START.md'),
        ('../README.md', 'README.md'),
        ('../render.yaml', 'render.yaml'),
        ('../server_setup.py', 'server_setup.py'),
        ('../setup.py', 'setup.py'),
        ('../setup.spec', 'setup.spec'),
        ('../TESTING_GUIDE.md', 'TESTING_GUIDE.md'),
        ('../unit_client.py', 'unit_client.py'),
        ('../unit_client.service', 'unit_client.service'),
        ('../vercel.json', 'vercel.json'),
        # Installation scripts
        ('server_manager.py', 'server_manager.py'),
        ('uninstall.py', 'uninstall.py'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.scrolledtext',
        'threading',
        'subprocess',
        'json',
        'shutil',
        'platform',
        'pathlib',
        'tempfile',
        'datetime',
        'ctypes',
        'ctypes.wintypes',
        'winreg',
        'PIL',
        'psutil',
        'requests',
        'dotenv',
        'flask',
        'flask_cors',
        'flask_socketio',
        'GPUtil',
        'sqlalchemy',
        'psycopg2',
        'uuid',
        'win32com.client',
        'win32com',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SysLogger_Server_Installer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='installer_icon.ico' if os.path.exists('installer_icon.ico') else None,
)